exec dbo.AddControl 'Template1', 'Header', 'Header image'
exec dbo.AddControl 'Template1', 'Left', 'Left column'
exec dbo.AddControl 'Template1', 'Center', 'Center column'
exec dbo.AddControl 'Template1', 'Right', 'Right column'

exec dbo.AddControl 'Template2', 'Left', 'Left column'
exec dbo.AddControl 'Template2', 'Center', 'Center column'
exec dbo.AddControl 'Template2', 'Right', 'Right column'

exec dbo.AddControl 'Template3', 'Header', 'Header image'
exec dbo.AddControl 'Template3', 'Left', 'Left column'
exec dbo.AddControl 'Template3', 'Left2', 'Left column2'
exec dbo.AddControl 'Template3', 'Center', 'Center column'
exec dbo.AddControl 'Template3', 'Center2', 'Center column2'
exec dbo.AddControl 'Template3', 'Right', 'Right column'
exec dbo.AddControl 'Template3', 'Right2', 'Right column2'
