exec dbo.AddPage 'template1', null, 'Template1', 'TemplateLink', 0
exec dbo.AddPage 'template2', null, 'Template2', 'TemplateLink', 0
exec dbo.AddPage 'template3', null, 'Template3', 'TemplateLink', 0
exec dbo.AddPage 'templatepage1', 'template1', null, 'TemplatePage', 0
exec dbo.AddPage 'templatepage2', 'template2', null, 'TemplatePage', 0
exec dbo.AddPage 'templatepage3', 'template3', null, 'TemplatePage', 0
exec dbo.AddPage 'welcome', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'uoi', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'ioi', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'union', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'camp', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'alluoi', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'allioi', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'allunion', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'about', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'problem', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'links', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'literatures', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'articles', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'deliveries', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'interviews', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'uoiresults', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'uoirating', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'literature', 'templatepage1', null, 'UserPage', 1
exec dbo.AddPage 'interview', 'templatepage1', null, 'UserPage', 1
